# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pybps',
                'doc_host': 'https://josephrilling.github.io',
                'git_url': 'https://github.com/josephrilling/pybps',
                'lib_path': 'pybps'},
  'syms': { 'pybps.bps': { 'pybps.bps.BPS': ('bps.html#bps', 'pybps/bps.py'),
                           'pybps.bps.BPS.__init__': ('bps.html#bps.__init__', 'pybps/bps.py'),
                           'pybps.bps.BPS.fit': ('bps.html#bps.fit', 'pybps/bps.py'),
                           'pybps.bps.BPS.predict': ('bps.html#bps.predict', 'pybps/bps.py')},
            'pybps.core': { 'pybps.core.BPS': ('bps.html#bps', 'pybps/core.py'),
                            'pybps.core.BPS.__init__': ('bps.html#bps.__init__', 'pybps/core.py'),
                            'pybps.core.BPS.fit': ('bps.html#bps.fit', 'pybps/core.py'),
                            'pybps.core.BPS.predict': ('bps.html#bps.predict', 'pybps/core.py')}}}
